/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;

import java.awt.Color;

/**
 *
 * @author Justin
 */
public class Compte extends javax.swing.JFrame {

    /**
     * Creates new form Compte
     */
    public Compte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelCompte = new javax.swing.JPanel();
        labelPseudonyme = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        labelPrenom = new javax.swing.JLabel();
        labelAdresseEmail = new javax.swing.JLabel();
        labelMDP = new javax.swing.JLabel();
        casePseudonyme = new javax.swing.JTextField();
        caseNom = new javax.swing.JTextField();
        casePrenom = new javax.swing.JTextField();
        caseAdresseEmail = new javax.swing.JTextField();
        caseMDP = new javax.swing.JPasswordField();
        underlineAdresseEmail = new javax.swing.JPanel();
        underlinePrenom = new javax.swing.JPanel();
        underlineNom = new javax.swing.JPanel();
        underlinePseudonyme = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(1280, 800));

        panelCompte.setBackground(new java.awt.Color(247, 247, 247));
        panelCompte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 76, 34), 2));

        labelPseudonyme.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        labelPseudonyme.setText("Pseudonyme :");

        labelNom.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        labelNom.setText("Nom :");

        labelPrenom.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        labelPrenom.setText("Prénom :");

        labelAdresseEmail.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        labelAdresseEmail.setText("Adresse email :");

        labelMDP.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        labelMDP.setText("Mot de passe :");

        casePseudonyme.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        casePseudonyme.setText("Just1");
        casePseudonyme.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                casePseudonymeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                casePseudonymeFocusLost(evt);
            }
        });

        caseNom.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        caseNom.setText("Sornay");

        casePrenom.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        casePrenom.setText("Justin");

        caseAdresseEmail.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        caseAdresseEmail.setText("justin.sornay@sfr.fr");

        caseMDP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        caseMDP.setText("jPasswordField1");

        underlineAdresseEmail.setBackground(new java.awt.Color(232, 76, 34));
        underlineAdresseEmail.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout underlineAdresseEmailLayout = new javax.swing.GroupLayout(underlineAdresseEmail);
        underlineAdresseEmail.setLayout(underlineAdresseEmailLayout);
        underlineAdresseEmailLayout.setHorizontalGroup(
            underlineAdresseEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        underlineAdresseEmailLayout.setVerticalGroup(
            underlineAdresseEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        underlinePrenom.setBackground(new java.awt.Color(232, 76, 34));
        underlinePrenom.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout underlinePrenomLayout = new javax.swing.GroupLayout(underlinePrenom);
        underlinePrenom.setLayout(underlinePrenomLayout);
        underlinePrenomLayout.setHorizontalGroup(
            underlinePrenomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        underlinePrenomLayout.setVerticalGroup(
            underlinePrenomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        underlineNom.setBackground(new java.awt.Color(232, 76, 34));
        underlineNom.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout underlineNomLayout = new javax.swing.GroupLayout(underlineNom);
        underlineNom.setLayout(underlineNomLayout);
        underlineNomLayout.setHorizontalGroup(
            underlineNomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        underlineNomLayout.setVerticalGroup(
            underlineNomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        underlinePseudonyme.setBackground(new java.awt.Color(232, 76, 34));
        underlinePseudonyme.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout underlinePseudonymeLayout = new javax.swing.GroupLayout(underlinePseudonyme);
        underlinePseudonyme.setLayout(underlinePseudonymeLayout);
        underlinePseudonymeLayout.setHorizontalGroup(
            underlinePseudonymeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        underlinePseudonymeLayout.setVerticalGroup(
            underlinePseudonymeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelCompteLayout = new javax.swing.GroupLayout(panelCompte);
        panelCompte.setLayout(panelCompteLayout);
        panelCompteLayout.setHorizontalGroup(
            panelCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompteLayout.createSequentialGroup()
                .addGroup(panelCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCompteLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(labelMDP)
                        .addGap(18, 18, 18)
                        .addComponent(caseMDP, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCompteLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(labelPseudonyme)
                        .addGap(18, 18, 18)
                        .addComponent(casePseudonyme, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCompteLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(labelPrenom)
                        .addGap(18, 18, 18)
                        .addComponent(casePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCompteLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(labelAdresseEmail)
                        .addGap(18, 18, 18)
                        .addComponent(caseAdresseEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCompteLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(labelNom)
                        .addGap(18, 18, 18)
                        .addComponent(caseNom, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(underlineAdresseEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addComponent(underlinePrenom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addComponent(underlineNom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addComponent(underlinePseudonyme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCompteLayout.setVerticalGroup(
            panelCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCompteLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(panelCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casePseudonyme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPseudonyme))
                .addGap(15, 15, 15)
                .addComponent(underlinePseudonyme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caseNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNom))
                .addGap(14, 14, 14)
                .addComponent(underlineNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrenom))
                .addGap(18, 18, 18)
                .addComponent(underlinePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAdresseEmail)
                    .addComponent(caseAdresseEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(underlineAdresseEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caseMDP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMDP))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(panelCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(panelCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void casePseudonymeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_casePseudonymeFocusGained

    }//GEN-LAST:event_casePseudonymeFocusGained

    private void casePseudonymeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_casePseudonymeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_casePseudonymeFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JTextField caseAdresseEmail;
    private javax.swing.JPasswordField caseMDP;
    private javax.swing.JTextField caseNom;
    private javax.swing.JTextField casePrenom;
    private javax.swing.JTextField casePseudonyme;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelAdresseEmail;
    private javax.swing.JLabel labelMDP;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelPrenom;
    private javax.swing.JLabel labelPseudonyme;
    private javax.swing.JPanel panelCompte;
    private javax.swing.JPanel underlineAdresseEmail;
    private javax.swing.JPanel underlineNom;
    private javax.swing.JPanel underlinePrenom;
    private javax.swing.JPanel underlinePseudonyme;
    // End of variables declaration//GEN-END:variables
}
