/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;

import java.awt.Color;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Justin
 */
public class Login extends javax.swing.JFrame {

    private boolean codeBon;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.codeBon = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        btnParametre = new javax.swing.JButton();
        btnInscription = new javax.swing.JButton();
        casePseudonyme = new javax.swing.JTextField();
        caseMDP = new javax.swing.JPasswordField();
        btnConnexion = new javax.swing.JButton();
        underlineCasePseudonyme = new javax.swing.JPanel();
        underlineCaseMDP = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));

        btnParametre.setBackground(new java.awt.Color(255, 255, 255));
        btnParametre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet/imgLogin/parametre-125%.png"))); // NOI18N
        btnParametre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnParametre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParametreActionPerformed(evt);
            }
        });

        btnInscription.setBackground(new java.awt.Color(255, 255, 255));
        btnInscription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet/imgLogin/inscription-125%.png"))); // NOI18N
        btnInscription.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInscription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnInscriptionFocusGained(evt);
            }
        });
        btnInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscriptionActionPerformed(evt);
            }
        });

        casePseudonyme.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        casePseudonyme.setForeground(new java.awt.Color(154, 154, 140));
        casePseudonyme.setText("Pseudonyme");
        casePseudonyme.setDisabledTextColor(new java.awt.Color(154, 154, 140));
        casePseudonyme.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                casePseudonymeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                casePseudonymeFocusLost(evt);
            }
        });
        casePseudonyme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casePseudonymeActionPerformed(evt);
            }
        });

        caseMDP.setForeground(new java.awt.Color(154, 154, 140));
        caseMDP.setText("jPasswordField1");
        caseMDP.setDisabledTextColor(new java.awt.Color(154, 154, 140));
        caseMDP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                caseMDPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                caseMDPFocusLost(evt);
            }
        });
        caseMDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseMDPActionPerformed(evt);
            }
        });

        btnConnexion.setBackground(new java.awt.Color(232, 76, 34));
        btnConnexion.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btnConnexion.setForeground(new java.awt.Color(255, 255, 255));
        btnConnexion.setText("Se connecter");
        btnConnexion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConnexion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnConnexionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnConnexionFocusLost(evt);
            }
        });
        btnConnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConnexionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnConnexionMouseReleased(evt);
            }
        });
        btnConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnexionActionPerformed(evt);
            }
        });

        underlineCasePseudonyme.setBackground(new java.awt.Color(232, 76, 34));
        underlineCasePseudonyme.setForeground(new java.awt.Color(232, 76, 34));
        underlineCasePseudonyme.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout underlineCasePseudonymeLayout = new javax.swing.GroupLayout(underlineCasePseudonyme);
        underlineCasePseudonyme.setLayout(underlineCasePseudonymeLayout);
        underlineCasePseudonymeLayout.setHorizontalGroup(
            underlineCasePseudonymeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        underlineCasePseudonymeLayout.setVerticalGroup(
            underlineCasePseudonymeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        underlineCaseMDP.setBackground(new java.awt.Color(232, 76, 34));
        underlineCaseMDP.setForeground(new java.awt.Color(232, 76, 34));
        underlineCaseMDP.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout underlineCaseMDPLayout = new javax.swing.GroupLayout(underlineCaseMDP);
        underlineCaseMDP.setLayout(underlineCaseMDPLayout);
        underlineCaseMDPLayout.setHorizontalGroup(
            underlineCaseMDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        underlineCaseMDPLayout.setVerticalGroup(
            underlineCaseMDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(443, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(underlineCasePseudonyme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                                .addComponent(casePseudonyme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(caseMDP)
                                .addComponent(underlineCaseMDP, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addComponent(btnConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(381, 381, 381))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addComponent(btnInscription)
                                .addGap(36, 36, 36)
                                .addComponent(btnParametre)))))
                .addGap(53, 53, 53))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnParametre)
                    .addComponent(btnInscription))
                .addGap(170, 170, 170)
                .addComponent(casePseudonyme, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underlineCasePseudonyme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(caseMDP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underlineCaseMDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(btnConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscriptionActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnInscriptionActionPerformed

    /*
    * Verification du MDP
    */
    private void btnConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnexionActionPerformed
        String pseudonymeSaisi = casePseudonyme.getText();
        
        PasswordHash p = new PasswordHash(caseMDP.getPassword());
        System.out.println(p.toString());
        
        try {
            if(p.goodMDP(pseudonymeSaisi)){
                this.codeBon = true;
            }
        } catch (SQLException ex) {
            //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, "Problème Login voir classe PasswordHash", ex);
            System.out.println(ex);
        }
        
        if(this.codeBon){
            new MenuNavigation().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnConnexionActionPerformed

    private void casePseudonymeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casePseudonymeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casePseudonymeActionPerformed

    private void casePseudonymeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_casePseudonymeFocusGained
        if(casePseudonyme.getText().equals("Pseudonyme")){
            casePseudonyme.setText("");
        }
         
        casePseudonyme.setForeground(Color.BLACK);
        underlineCasePseudonyme.setSize(450, 5);
    }//GEN-LAST:event_casePseudonymeFocusGained

    private void casePseudonymeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_casePseudonymeFocusLost
        if(casePseudonyme.getText().equals("")){
            casePseudonyme.setText("Pseudonyme");
        }
         
        casePseudonyme.setForeground(new Color(154,154,140));
        underlineCasePseudonyme.setSize(450, 2);
    }//GEN-LAST:event_casePseudonymeFocusLost

    private void caseMDPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caseMDPFocusGained
        if(caseMDP.getText().equals("jPasswordField1")){
            caseMDP.setText("");
        }
         
        caseMDP.setForeground(Color.BLACK);   
        underlineCaseMDP.setSize(450, 5);
    }//GEN-LAST:event_caseMDPFocusGained

    private void caseMDPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caseMDPFocusLost
        if(caseMDP.getText().equals("")){
            caseMDP.setText("jPasswordField1");
        }
         
        caseMDP.setForeground(new Color(154,154,140));    
        underlineCaseMDP.setSize(450, 2);
    }//GEN-LAST:event_caseMDPFocusLost

    private void btnInscriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnInscriptionFocusGained

    }//GEN-LAST:event_btnInscriptionFocusGained

    private void btnParametreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParametreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnParametreActionPerformed

    private void btnConnexionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnConnexionFocusGained
       
    }//GEN-LAST:event_btnConnexionFocusGained

    private void btnConnexionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnConnexionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConnexionFocusLost

    private void btnConnexionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnexionMousePressed
        btnConnexion.setBackground(Color.WHITE);
        btnConnexion.setForeground(new Color(232,76,34));
        
        
    }//GEN-LAST:event_btnConnexionMousePressed

    private void btnConnexionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnexionMouseReleased
        btnConnexion.setBackground(new Color(232,76,34));
        btnConnexion.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnConnexionMouseReleased

    /*
    * Répurération du mdp en hashage
    */
    private void caseMDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseMDPActionPerformed
        // TODO add your handling code here:
        PasswordHash p = new PasswordHash(caseMDP.getPassword());
        System.out.println(p.toString());
        
    }//GEN-LAST:event_caseMDPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnConnexion;
    private javax.swing.JButton btnInscription;
    private javax.swing.JButton btnParametre;
    private javax.swing.JPasswordField caseMDP;
    private javax.swing.JTextField casePseudonyme;
    private javax.swing.JPanel underlineCaseMDP;
    private javax.swing.JPanel underlineCasePseudonyme;
    // End of variables declaration//GEN-END:variables
}
