/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;

/**
 *
 * @author Justin
 */
public class MenuNavigation extends javax.swing.JFrame {

    /**
     * Creates new form MenuNavigation
     */
    public MenuNavigation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        btnParametre = new javax.swing.JButton();
        btnListeProjet = new javax.swing.JButton();
        btnCompte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));

        btnParametre.setBackground(new java.awt.Color(255, 255, 255));
        btnParametre.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        btnParametre.setForeground(new java.awt.Color(232, 76, 34));
        btnParametre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet/imgMenuNavigation/parametres-nav.png"))); // NOI18N
        btnParametre.setText("Paramètres");
        btnParametre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnParametre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParametreActionPerformed(evt);
            }
        });

        btnListeProjet.setBackground(new java.awt.Color(255, 255, 255));
        btnListeProjet.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        btnListeProjet.setForeground(new java.awt.Color(232, 76, 34));
        btnListeProjet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet/imgMenuNavigation/listeProjet.png"))); // NOI18N
        btnListeProjet.setText("Liste des projets");
        btnListeProjet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListeProjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeProjetActionPerformed(evt);
            }
        });

        btnCompte.setBackground(new java.awt.Color(255, 255, 255));
        btnCompte.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        btnCompte.setForeground(new java.awt.Color(232, 76, 34));
        btnCompte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet/imgMenuNavigation/compte.png"))); // NOI18N
        btnCompte.setText("Compte");
        btnCompte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(btnCompte, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnParametre, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addComponent(btnListeProjet, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(btnListeProjet, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompte, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParametre, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnParametreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParametreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnParametreActionPerformed

    private void btnListeProjetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeProjetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListeProjetActionPerformed

    private void btnCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCompteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuNavigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuNavigation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnCompte;
    private javax.swing.JButton btnListeProjet;
    private javax.swing.JButton btnParametre;
    // End of variables declaration//GEN-END:variables
}
