/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;

import java.awt.Color;

/**
 *
 * @author Justin
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        casePseudonyme = new javax.swing.JTextField();
        caseNom = new javax.swing.JTextField();
        casePrenom = new javax.swing.JTextField();
        caseAdresseMail = new javax.swing.JTextField();
        caseMDP = new javax.swing.JPasswordField();
        btnInscription = new javax.swing.JButton();
        underlineCasePseudonyme = new javax.swing.JPanel();
        underlineCaseNom = new javax.swing.JPanel();
        underlineCasePrenom = new javax.swing.JPanel();
        underlineCaseAdresseMail = new javax.swing.JPanel();
        underlineCaseMDP = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));

        casePseudonyme.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        casePseudonyme.setForeground(new java.awt.Color(154, 154, 140));
        casePseudonyme.setText("Pseudonyme");
        casePseudonyme.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                casePseudonymeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                casePseudonymeFocusLost(evt);
            }
        });
        casePseudonyme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casePseudonymeActionPerformed(evt);
            }
        });

        caseNom.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        caseNom.setForeground(new java.awt.Color(154, 154, 140));
        caseNom.setText("Nom");
        caseNom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                caseNomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                caseNomFocusLost(evt);
            }
        });

        casePrenom.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        casePrenom.setForeground(new java.awt.Color(154, 154, 140));
        casePrenom.setText("Prénom");
        casePrenom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                casePrenomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                casePrenomFocusLost(evt);
            }
        });

        caseAdresseMail.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        caseAdresseMail.setForeground(new java.awt.Color(154, 154, 140));
        caseAdresseMail.setText("Adresse mail");
        caseAdresseMail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                caseAdresseMailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                caseAdresseMailFocusLost(evt);
            }
        });

        caseMDP.setForeground(new java.awt.Color(154, 154, 140));
        caseMDP.setText("jPasswordField1");
        caseMDP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                caseMDPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                caseMDPFocusLost(evt);
            }
        });

        btnInscription.setBackground(new java.awt.Color(232, 76, 34));
        btnInscription.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btnInscription.setForeground(new java.awt.Color(255, 255, 255));
        btnInscription.setText("S'inscire");
        btnInscription.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInscriptionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnInscriptionMouseReleased(evt);
            }
        });
        btnInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscriptionActionPerformed(evt);
            }
        });

        underlineCasePseudonyme.setBackground(new java.awt.Color(232, 76, 34));
        underlineCasePseudonyme.setForeground(new java.awt.Color(232, 76, 34));

        javax.swing.GroupLayout underlineCasePseudonymeLayout = new javax.swing.GroupLayout(underlineCasePseudonyme);
        underlineCasePseudonyme.setLayout(underlineCasePseudonymeLayout);
        underlineCasePseudonymeLayout.setHorizontalGroup(
            underlineCasePseudonymeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        underlineCasePseudonymeLayout.setVerticalGroup(
            underlineCasePseudonymeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        underlineCaseNom.setBackground(new java.awt.Color(232, 76, 34));
        underlineCaseNom.setForeground(new java.awt.Color(232, 76, 34));

        javax.swing.GroupLayout underlineCaseNomLayout = new javax.swing.GroupLayout(underlineCaseNom);
        underlineCaseNom.setLayout(underlineCaseNomLayout);
        underlineCaseNomLayout.setHorizontalGroup(
            underlineCaseNomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        underlineCaseNomLayout.setVerticalGroup(
            underlineCaseNomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        underlineCasePrenom.setBackground(new java.awt.Color(232, 76, 34));
        underlineCasePrenom.setForeground(new java.awt.Color(232, 76, 34));

        javax.swing.GroupLayout underlineCasePrenomLayout = new javax.swing.GroupLayout(underlineCasePrenom);
        underlineCasePrenom.setLayout(underlineCasePrenomLayout);
        underlineCasePrenomLayout.setHorizontalGroup(
            underlineCasePrenomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        underlineCasePrenomLayout.setVerticalGroup(
            underlineCasePrenomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        underlineCaseAdresseMail.setBackground(new java.awt.Color(232, 76, 34));
        underlineCaseAdresseMail.setForeground(new java.awt.Color(232, 76, 34));

        javax.swing.GroupLayout underlineCaseAdresseMailLayout = new javax.swing.GroupLayout(underlineCaseAdresseMail);
        underlineCaseAdresseMail.setLayout(underlineCaseAdresseMailLayout);
        underlineCaseAdresseMailLayout.setHorizontalGroup(
            underlineCaseAdresseMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        underlineCaseAdresseMailLayout.setVerticalGroup(
            underlineCaseAdresseMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        underlineCaseMDP.setBackground(new java.awt.Color(232, 76, 34));
        underlineCaseMDP.setForeground(new java.awt.Color(232, 76, 34));

        javax.swing.GroupLayout underlineCaseMDPLayout = new javax.swing.GroupLayout(underlineCaseMDP);
        underlineCaseMDP.setLayout(underlineCaseMDPLayout);
        underlineCaseMDPLayout.setHorizontalGroup(
            underlineCaseMDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        underlineCaseMDPLayout.setVerticalGroup(
            underlineCaseMDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(btnInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(caseMDP)
                                .addComponent(caseAdresseMail)
                                .addComponent(casePrenom)
                                .addComponent(underlineCasePrenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(underlineCaseAdresseMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(underlineCaseMDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(caseNom)
                                .addComponent(casePseudonyme)
                                .addComponent(underlineCasePseudonyme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(underlineCaseNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(431, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(casePseudonyme, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underlineCasePseudonyme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(caseNom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underlineCaseNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(casePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underlineCasePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(caseAdresseMail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underlineCaseAdresseMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(caseMDP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underlineCaseMDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(btnInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscriptionActionPerformed
        String pseudonymeSaisi = casePseudonyme.getText();
        String nomSaisi = caseNom.getText();
        String prenomSaisi = casePrenom.getText();
        String adresseMailSaisi = caseAdresseMail.getText();
        char[] mdpSaisi = caseMDP.getPassword();
    }//GEN-LAST:event_btnInscriptionActionPerformed

    private void casePseudonymeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_casePseudonymeFocusGained
        if(casePseudonyme.getText().equals("Pseudonyme")){
            casePseudonyme.setText("");
        }
         
        casePseudonyme.setForeground(Color.BLACK);
        underlineCasePseudonyme.setSize(450, 5);
    }//GEN-LAST:event_casePseudonymeFocusGained

    private void casePseudonymeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_casePseudonymeFocusLost
        if(casePseudonyme.getText().equals("")){
            casePseudonyme.setText("Pseudonyme");
        }
         
        casePseudonyme.setForeground(new Color(154,154,140));
        underlineCasePseudonyme.setSize(450, 2);        
    }//GEN-LAST:event_casePseudonymeFocusLost

    private void caseNomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caseNomFocusGained
        if(caseNom.getText().equals("Nom")){
            caseNom.setText("");
        }
         
        caseNom.setForeground(Color.BLACK);
        underlineCaseNom.setSize(450, 5);
    }//GEN-LAST:event_caseNomFocusGained

    private void caseNomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caseNomFocusLost
        if(caseNom.getText().equals("")){
            caseNom.setText("Nom");
        }
         
        caseNom.setForeground(new Color(154,154,140));
        underlineCaseNom.setSize(450, 2);
    }//GEN-LAST:event_caseNomFocusLost

    private void casePrenomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_casePrenomFocusGained
        if(casePrenom.getText().equals("Prénom")){
            casePrenom.setText("");
        }
         
        casePrenom.setForeground(Color.BLACK);
        underlineCasePrenom.setSize(450, 5);
    }//GEN-LAST:event_casePrenomFocusGained

    private void casePrenomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_casePrenomFocusLost
        if(casePrenom.getText().equals("")){
            casePrenom.setText("Prénom");
        }
         
        casePrenom.setForeground(new Color(154,154,140));
        underlineCasePrenom.setSize(450, 2);
    }//GEN-LAST:event_casePrenomFocusLost

    private void caseAdresseMailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caseAdresseMailFocusGained
        if(caseAdresseMail.getText().equals("Adresse mail")){
            caseAdresseMail.setText("");
        }
         
        caseAdresseMail.setForeground(Color.BLACK);
        underlineCaseAdresseMail.setSize(450, 5);
    }//GEN-LAST:event_caseAdresseMailFocusGained

    private void caseAdresseMailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caseAdresseMailFocusLost
        if(caseAdresseMail.getText().equals("")){
            caseAdresseMail.setText("Adresse mail");
        }
         
        caseAdresseMail.setForeground(new Color(154,154,140));
        underlineCaseAdresseMail.setSize(450, 2);
    }//GEN-LAST:event_caseAdresseMailFocusLost

    private void caseMDPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caseMDPFocusGained
        if(caseMDP.getText().equals("jPasswordField1")){
            caseMDP.setText("");
        }
         
        caseMDP.setForeground(Color.BLACK);
        underlineCaseMDP.setSize(450, 5);
    }//GEN-LAST:event_caseMDPFocusGained

    private void caseMDPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caseMDPFocusLost
        if(caseMDP.getText().equals("")){
            caseMDP.setText("jPasswordField1");
        }
         
        caseMDP.setForeground(new Color(154,154,140));
        underlineCaseMDP.setSize(450, 2);
    }//GEN-LAST:event_caseMDPFocusLost

    private void casePseudonymeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casePseudonymeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casePseudonymeActionPerformed

    private void btnInscriptionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInscriptionMousePressed
        btnInscription.setBackground(Color.WHITE);
        btnInscription.setForeground(new Color(232,76,34));
        new Login().setVisible(true);
    }//GEN-LAST:event_btnInscriptionMousePressed

    private void btnInscriptionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInscriptionMouseReleased
        btnInscription.setBackground(new Color(232,76,34));
        btnInscription.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnInscriptionMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnInscription;
    private javax.swing.JTextField caseAdresseMail;
    private javax.swing.JPasswordField caseMDP;
    private javax.swing.JTextField caseNom;
    private javax.swing.JTextField casePrenom;
    private javax.swing.JTextField casePseudonyme;
    private javax.swing.JPanel underlineCaseAdresseMail;
    private javax.swing.JPanel underlineCaseMDP;
    private javax.swing.JPanel underlineCaseNom;
    private javax.swing.JPanel underlineCasePrenom;
    private javax.swing.JPanel underlineCasePseudonyme;
    // End of variables declaration//GEN-END:variables
}
